server:
    port: 8080

spring:
    datasource:
        name: dev
        url: jdbc:mysql://localhost:3306/concurrent?serverTimezone=GMT%2B8
        username: root
        password: 123456

mybatis:
    mapper-locations: "com/poldichen/democoncurrent/dao/mapper/*.xml"